server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: fc11
    password:
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

#    datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    open-in-view: true


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration: ${JWT_ACCESS_EXPIRATION_MIN}
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION_MIN}

logging:
  level:
    '[fastcampus.scheduling]': DEBUG
    '[org.hibernate.type]': TRACE