server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  security:
    user:
      name: admin
      password: 8a2e8626-fdb1-4f37-8fe9-1e23d3a62601

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: fc11
    password:
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

#    datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    open-in-view: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          debug: true
          starttls:
            enable: true


